exclude: \.(ipynb|nblink)$
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-merge-conflict
    - id: check-toml
    - id: check-yaml
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort
      args: ["--profile", "black"]
      exclude: (aesara_federated/rpc.py|aesara_federated/npproto/)
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black
      exclude: (aesara_federated/rpc.py|aesara_federated/npproto/)
