name: ptfenv
channels:
  - conda-forge
dependencies:
  - black
  - isort
  - nest-asyncio
  - numpy
  - pytest
  - pytest-cov
  - pip
  - psutil
  - pip:
    - betterproto[compiler]==2.0.0b6
    - pymc==5.10.0
